import os

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHROMA_DB_DIR = os.path.join(BASE_DIR, "chroma_db")

# Models
EMBEDDING_MODEL_NAME = "all-mpnet-base-v2"
LLM_MODEL_NAME = "llama3.1:8b"

# Ingestion Settings
WIKI_LANG = "en"  
WIKI_TOPICS = [
    "Artificial Intelligence",
    "ChatGPT",
    "Gemini (language model)",
    "Hallucination (artificial intelligence)",
    "BERT (language model)",
    "Transformer (deep learning)",
    "Computer",
    "Learning",
    "Reason",
    "Problem solving",
    "Perception",
    "Decision-making",
    "Computer science",
    "Software",
    "Computer programming",
    "Computer hardware",
    "Operating system",
    "Mobile device",
    "Internet",
    "Digital data",
    "Transistor",
    "Central processing unit",
    "Computer memory",
    "Random-access memory",
    "Robotics",
    "Statistics",
    "Deep learning",
    "Algorithm",
    "Machine",
    "Generative pre-trained transformer",
    "Medicine",
    "Medical genetics",
    "Cell (biology)",
    "Brain",
    "Organ (biology)",
    "Surgery",
    "Radiology",
    "Medical research",
    "Anatomy",
    "Organism",
    "Biochemistry",
    "Endocrinology",
    "Genetics",
    "Neuroscience",
    "Biophysics",
    "Molecule",
    "Atom",
    "Proton",
    "Neutron",
    "Electron",
    "Quantum mechanics",
    "Physics",
    "Oxygen",
    "Water",
    "Rock (geology)",
    "Metal",
    "Electric current",
    "Ion",
    "Electrical conductor",
    "Electric charge",
    "Semiconductor",
    "Plasma (physics)",
    "Magnetic field",
    "Inductor",
    "Light",
    "Matter",
    "Sun",
    "Star",
    "Galaxy",
    "Gravity",
    "Solar System",
    "Nuclear fusion",
    "Earth",
    "Planet",
    "Fire",
    "Photon",
    "Vacuum",
    "Space",
    "Natural satellite",
    "Moon",
    "Jupiter",
    "Matter",
    "Ice",
    "Steam",
    "Saline water",
    "Salt (chemistry)",
    "Plastic",
    "History",
    "Human history",
    "Prehistory",
    "Periodization",
    "Holocene",
    "Post-classical history",
    "Modern era",
    "Ancient history",
    "Ancient Greece",
    "History of China",
    "Social science",
    "Philosophy",
    "Politics"
]

CHUNK_SIZE = 150 
CHUNK_OVERLAP = 15 
